### ISSUE TITLE
Clicking notifications sends to blank page

### ISSUE THREAD

**Issue by unklebonehead** [ecency/ecency-vision#1026]
When clicking on notifications they open as normal.
But clicking on individual notification it sends to blank page. (Screenshots are in discord issues room)
Vision 3.0.26
OS - Pop!OS 22.04 (Ubuntu 22.04)
Fully updated/upgraded on all packages
Screenshot 1
https://cdn.discordapp.com/attachments/385448634197737484/1021104381996839052/click-note.png
Screenshot 2
https://cdn.discordapp.com/attachments/385448634197737484/1021104382445625394/blan-ecency.png
Screenshot Neofetch with computer info

**Comment by stresskiller** [comment]
have the same issue on Windows 11 + firefox

**Comment by unklebonehead** [comment]
Closing this issue as its now been fixed for me.

**Comment by unklebonehead** [comment]
Closed for me
