### ISSUE TITLE
Notifications drawer improvements

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#1038]
Make sure user menu is visible, right now drawer takes entire screen height, but goal is to make it more like dropdown style, while user menu and notification bell is still visible

**Comment by Adesojisouljay** [comment]
### What does this PR ?

This PR makes sure that user menu is visible when notification is clicked.

### Issue link
[Find issue here](https://github.com/ecency/ecency-vision/issues/1038)

### Screenshot/video
[View on loom](https://www.loom.com/share/0c410ba21eda4aca94cc66179841709a)
