### ISSUE TITLE
Add slider solver 

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#1047]
like binance on login form,
human check

**Comment by MTSaeed** [comment]
Hi @feruzm , I did some research this and found out that a similar slide solver same as Binance is being provided by https://www.geetest.com/ . I have tried implementing this by making a trial account and integrating the slider in a test project. I am attaching the video for reference. Kindly tell if we can use this slider or should be following a different approach.

**Comment by MTSaeed** [comment]
We can try google capcha
