### ISSUE TITLE
Show all promoted content in one page/filter.

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#1057]
Right now you can see Sponsored or promoted content in feeds every 3rd post. We have randomized them, but now we can create page where we can show all of them by fetching from API and fetching content of each post from dhive.

**Comment by MTSaeed** [comment]
Hi @feruzm I cannot get promoted posts on local system. Please tell if there is something specific we need to do for this. I have logged the results of API, the list for promoted content is empty. I cannot see any promoted posts in the feed either. But promoted posts are available on ecency.com

Please advise. Thanks
