### ISSUE TITLE
Design and implement footer banner

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#1085]
Design and implement footer banner for important announcements with dismiss, yes, no, later type of actionable buttons, timer dismiss. Later can be done like telegram, timer and with undo where you can undo certain action if you change your mind within 3 seconds for example.

**Comment by MTSaeed** [comment]
@feruzm Please tell on which pages should we show this banner. Please also tell which API call will be used for this task.

**Comment by MTSaeed** [comment]
Two buttons : Dismiss, Action Button: Have text according to the context. "Learn More" in beginning, Later Button: this will show reminder to the user. 

Have an announcement.json file at the server side and have information about the announcement,
