### ISSUE TITLE
Bug: Editor Advanced section images are not showing

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#1147]
In editor advanced section, images are not showing to select thumbnail of the post. So post creation not allowing thumbnail selection, it was working before, perhaps some new changes, removed or broke it. Find out and improve logic.

**Comment by igormuba** [comment]
Fix at
https://github.com/ecency/ecency-vision/pull/1148

**Comment by feruzm** [comment]
@igormuba next time, in PR description or commits messages, add `Fixes #1147` message referencing this issue number. Once PR merged, it should automatically close this issue as well with it.
