### ISSUE TITLE
Animation after vote is cast

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#1149]
Right now, we have blinking animation while vote is processed/submitted, try to improve that after vote cast with animation.
We increase heart number so animation could be checked to do on heart icon or on vote icon. Best to see different variations and see if there can be structure for that animation to be configurable in future.

Something like this: 
https://lottiefiles.com/88955-reddit-up-vote
https://lottiefiles.com/96937-like-heart
https://lottiefiles.com/88219-upvote-splash-animation
https://lottiefiles.com/9729-upvote

**Comment by igormuba** [comment]
Hi, I am not sure if I understood the task.
I didn't understand the wording "We increase heart number ", what is that supposed to mean?

Other than that, in general, is it just to make it more clear that an animation is happening?

**Comment by igormuba** [comment]
At 
https://animista.net/play/basic/rotate-scale
I found some easy to use animations

I just had to add to the file src/style/_animation.scss
```
@-webkit-keyframes rotate-scale-up {
  0% {
    -webkit-transform: scale(1) rotateZ(0);
    transform: scale(1) rotateZ(0);
  }
  50% {
    -webkit-transform: scale(2) rotateZ(180deg);
    transform: scale(2) rotateZ(180deg);
  }
  100% {
    -webkit-transform: scale(1) rotateZ(360deg);
    transform: scale(1) rotateZ(360deg);
  }
}
@keyframes rotate-scale-up {
  0% {
    -webkit-transform: scale(1) rotateZ(0);
    transform: scale(1) rotateZ(0);
  }
  50% {
    -webkit-transform: scale(2) rotateZ(180deg);
    transform: scale(2) rotateZ(180deg);
  }
  100% {
    -webkit-transform: scale(1) rotateZ(360deg);
    transform: scale(1) rotateZ(360deg);
  }
}
```

And then on src/style/_mixins.scss I on line 355 where it says `&.in-progress {` I add the new animation to play only once and leave the blinking animation playing for as long as it takes:
```
&.in-progress {
    animation: rotate-scale-up 0.65s linear both, anim-fadein-out 1s infinite;
    pointer-events: none;
  }
```

I like how subtly the original animation is but it is possible to make it more appearant, just need to decide what to do with it

**Comment by feruzm** [comment]
Animations are something to be considerate about and we would like to add more of them in future. So to keep that in we need to go with most scalable solution that doesn't increase much of overall bundle size as well.

- Image transfer animation, not device friendly or might have limited support on different devices, relatively bigger payload for users
- Lottie animations easiest to integrate but bundle size will increase a lot.
- Styling animations are tricky and hard to scale and manage in long run, but something we can start with. Because it is simpler and perhaps device support is wider compared to few years ago.

For technicality, Yes, I would suggest creating separate scss file `_animations.scss` so we combine all in single place.

**Comment by igormuba** [comment]
@feruzm I did create the file to test and ir works, we can use that, but I honestly have no idea where to go from here. I did take a look at other platforms and they seem to use CSS animations.

Got any suggestions of where to go from here? And what specifically to aim to do? I am lost

**Comment by feruzm** [comment]
@igormuba now that we have couple animation styles, goal is to connect those for vote operation or after vote operation so that heart icon can be animated after its component updates. Check how voting button animation is done with in-progress class, similar use of class should be added into `heart` icon to animate that.
