### ISSUE TITLE
Main filters rethinking

### ISSUE THREAD

**Issue by Adesojisouljay** [ecency/ecency-vision#1346]
https://www.loom.com/share/a6909a062fce4e4ab3049826868c55e0

**Comment by feruzm** [comment]
@Adesojisouljay this is fixed already, please check latest ecency.com

**Comment by Adesojisouljay** [comment]
Yeah, I just found out, on ecency.com, I haven't pulled recent changes to
development

**Comment by Adesojisouljay** [comment]
issue fixed on last release
