### ISSUE TITLE
Is Hivemind a requirement?

### ISSUE THREAD

**Issue by frankydev1** [ecency/ecency-vision#284]
It seems Hivemind is a requirement for some features such as "discover" as that makes a lot of calls?
Is Hivemind a requirement for login?  It seems that it also tries to make /api calls when logging in accessing hivemind?

Thank You

**Comment by feruzm** [comment]
Hi
Yes, we have connection to hivemind db. We are exploring options to replace it with public api endpoints like hivesearcher or use some blockchain apis. Login is not dependent on hivemind though. We have private api endpoint though used in our services like drafts, bookmarks, pointing system, etc.
