### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Mahdi321** [ecency/ecency-vision#289]
how do I set socks proxy?

**Comment by feruzm** [comment]
@Mahdi321 Did you mean, how to set proxy voting to another account ? Check witness page: https://ecency.com/witnesses

**Comment by feruzm** [comment]
closing for now, if you experience any issues, please reopen or provide more details! thanks!

**Comment by mahdi-cll** [comment]
No I mean proxy for connection.
There is a Russian made windows open-source proxifier but it does'nt work.
(I have to use windows (it is rdp service selection. beside using Linux is safe when you are using open-source hardware, too)

**Comment by feruzm** [comment]
Could you share link to that opensource so we can take a look, please? Thanks!

**Comment by mahdi-cll** [comment]
http://www.freecap.ru
http://widecap.com/
