### ISSUE TITLE
Desktop: Option to copy the link of a post

### ISSUE THREAD

**Issue by tibfox** [ecency/ecency-vision#323]
For the sake of sharing a post in dms it would be helpful to have a "copy link" button next to the reddit/twitter/fb share options. I personally am running a curation inititative and for that I need an easy way to copy the link to ecency.com/... with a single click.
![Unbenannt](https://user-images.githubusercontent.com/6019754/103519668-36f40000-4e76-11eb-9872-ed29025a195c.png)

**Comment by feruzm** [comment]
Looks like a good addition, thanks for suggestion! We will consider adding that in upcoming release of 3.0.12. Today website will receive major update and same update we will be bundled to desktop app in midweek.

**Comment by feruzm** [comment]
Done, added into last version.
