### ISSUE TITLE
Incorrect reference to posting key when trying to add private key to hivekeychain

### ISSUE THREAD

**Issue by 4Ykw** [ecency/ecency-vision#540]
Hi there,

Found it finally!

https://github.com/ecency/ecency-vision/blob/284d34b76fc408dda19a32fc7c3821fc48f0bd84/src/common/pages/communities.tsx#L405

**Comment by 4Ykw** [comment]
PR https://github.com/ecency/ecency-vision/pull/541 into development branch.

**Comment by feruzm** [comment]
Merged!
