### ISSUE TITLE
Suggestion: Honor `prefers-color-scheme` and change theme cookie lifespan

### ISSUE THREAD

**Issue by mciszczon** [ecency/ecency-vision#603]
I have a suggestion to enhance the Ecency browser app by either (or both) making it honor the `prefers-color-scheme` CSS media to automatically turn on the night mode, even when a cookie for that is not set.

Another proposition from me is to extend the lifespan of theme cookie. Currently it's a session cookie only, so once I restart the browser (or restart the PC, or reboot into a different OS) I have to go and change the theme again. Very frustrating. IMHO the `expires` value could be set to something arbitrarily high, like half a year or one year maybe.

I could theoretically do a PR with these, as these two changes should be no-brainers, but:

1. I am not sure whether these changes would be a gladly welcomed additions.
2. At this time I lack the free time to get to this.

So I am leaving it here for consideration, hoping for a feedback :)

**Comment by feruzm** [comment]
@mciszczon looks like a great additions, feel free to do a PR, of course we will consider and happy to see you contribute, in same PR please add your username in contributors.json so you will be listed in https://ecency.com/contributors. If any questions, issues feel free let us know.

**Comment by mciszczon** [comment]
@feruzm Okay, I'll try to make a PR next week, thanks for the feedback!
