### ISSUE TITLE
Pinning post into blog

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#774]
2 parts:

1. Operation is simply updating account `posting_json_metadata` with additional field `"pinned": "permlink"` example, permlink is post permlink. This operation should be added into 3 dot menu when you are viewing your own post.
2. Ability to show that pinned post if exist on account's `posting_json_metadata` as `pinned` field on top of all blog entries.

**Comment by adilrime17** [comment]
@feruzm @mghazanfar 
I can see we have some implementation of a pin or unpin the item in our component. But I can not relate this with the UI. Can you tell me the scenarios where we can pin or unpin the item?
It generally relates to community, active user, and some type of ROLES in the implementation.
