### ISSUE TITLE
Bug: Downvote mana/indicator 

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#799]
Downvote always showing 100% while actual value is low.

**Comment by mghazanfar** [comment]
@feruzm If I downvote 2 different posts with 2 different values and try to downvote third one, third one  has 0 default value. What should it be? the latest downvoted value?

**Comment by feruzm** [comment]
@mghazanfar this is about indicator not voting value. Click on user menu after login or click on i icon on profile page, you will see information about downvote percentage.
