### ISSUE TITLE
Blank page for Hive wallet on 3.0.20

### ISSUE THREAD

**Issue by unklebonehead** [ecency/ecency-vision#844]
Just installed 3.0.20 .deb on UbuntuStudio 21.10 Get a blank page when trying to view the Hive wallet. The Ecency wallet displays fine but not the Hive wallet. Doesnt matter what you use to get to it. Either directly through the menu in upper right or on the wallet tab in the settings page.
I tried signing in and out with Hivesigner and without Hivesigner. 
3.0.19 did not have this issue.
![Screenshot_20220203_152311](https://user-images.githubusercontent.com/16190983/152424616-d122f075-4567-4966-9498-e6e495526504.png)

**Comment by feruzm** [comment]
@unklebonehead thank you for report, yes wallet page was broken, we have just now released new version, could you please try that? https://github.com/ecency/ecency-vision/releases

**Comment by unklebonehead** [comment]
I see how you are! LOL! Installing now!

**Comment by unklebonehead** [comment]
And just like that it works!
