### ISSUE TITLE
BUG: First start on deb & appimage 3.0.23

### ISSUE THREAD

**Issue by unklebonehead** [ecency/ecency-vision#914]
When launching Ecency on both the appimage or deb. After logging in with Hivesigner nothing is displayed other than the bar at the top. 
When click on profile pic in right top and view profile. All works. I can then go to the normal feeds. 
This only happens on the first login. Everything works as normal after that. Including logging out. Restarting app an logging in again. Works great.

This is tested on Ubuntu 22.04 (intel) both appimage and the deb package.

Also tested appimage on Arch (amd). Same result after first log in. All others are normal.

**Comment by feruzm** [comment]
Thank you for report! We will check and include fix with upcoming new version.
