### ISSUE TITLE
Bug: Drafts not saving payout type.

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#922]
use `meta` object field from api to save everything missing:
payout type, beneficiaries, description, thumbnail, etc. And parse them when draft is opened again.

Relevant mobile app PR: https://github.com/ecency/ecency-mobile/pull/2356

**Comment by MTSaeed** [comment]
@feruzm I have tested and it seems to work already. I can see that Reward type is being save and retrieved properly. Please clarify if you mean to check the saving of existing fields on the drafts or adding new fields in the drafts that are there in the metadata but no input for them is there in drafts.

**Comment by feruzm** [comment]
@MTSaeed Please check if payout type is being send to backend inside `meta` json field and it is being set correctly when fetching and opening draft again. Some data we might be storing on localstorage, but we should be using backend api `meta` field.

**Comment by MTSaeed** [comment]
@feruzm I have noticed that payout type , beneficiaries, and all other data is send to backend at the time of adding the draft in the API and when drafts is load again it fetches the data from the backend API and show to the user.
According to my understanding payout means rewardType. is it right or payout means anything else?
Kindly verify. Thanks.


https://user-images.githubusercontent.com/106739598/230613278-f81d779e-44b0-43ad-869f-e988354ad227.mp4

**Comment by feruzm** [comment]
@MTSaeed yes that’s correct! In that case we can safely close this as it looks like outdated!
