### ISSUE TITLE
Bug: Grid view doesn't have pin to blog options

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#926]

**Comment by dkildar** [comment]
1. After pinning post it won't pin visually: something happens with sorting, but pinned post is previous not current. It will fix after page reloading
2. I also noticed sometimes if I change page to another user's account I briefly see pinned post by previous account's page
3. Grid view has too much space around images for some reason

**Comment by feruzm** [comment]
#932 fixed this
