### ISSUE TITLE
Bug: Brave browser history back

### ISSUE THREAD

**Issue by dkildar** [ecency/ecency-vision#934]
When I klick on the :ecency: it opens the feed, can choose new friend whatever, it works. 
I klick on a post, this opens.
But when I klick browsers back button, the feed is empty. Also refreching doesnt change, it stays empty.
Only solution: through my wallet - to Blogs - opening one of my posts. Only than I can klick :ecency:  again and see the feed 

With "hot" for example, going back this blue reloading bearn appears, but not with 'friends"

**Comment by feruzm** [comment]
fixed in #935
