### ISSUE TITLE
Cant vote for witnes or proposals on mobile web browser

### ISSUE THREAD

**Issue by unklebonehead** [ecency/ecency-vision#937]
When logged into the web on mobile device. Attempting to vote for a witness does not work. The pop up asking for active key or Hivesigner does not pop up. 
Using :
Brave mobile browser - myself
Samsung S21 confirmed - myself
Android 12
Chrome - Other user
Android 10

Both same results.

**Comment by feruzm** [comment]
New update which is coming this week, will have a fix! Thank you for reporting this.
