### ISSUE TITLE
Comment box is reduced in size in appimage version. 

### ISSUE THREAD

**Issue by unklebonehead** [ecency/ecency-vision#950]
Comment box on appimage 3.0.23 is reduced in iinput area. (See attached image).
 
Does this on Arch Linux and UbuntuMATE. The deb on UbuntuMATE does not do this. 

![this image](https://cdn.discordapp.com/attachments/385448634197737484/993296497909186590/ecency-comment-bos-appimage.png)

**Comment by unklebonehead** [comment]
It now does this on the .deb too
Pop!OS 22.04 (Ubuntu based)
Cosmic desktop (Gnome desktop)

**Comment by unklebonehead** [comment]
Windows 11 user reported it as well in the discord server.
Along with being unable to turn off notificattions.

**Comment by feruzm** [comment]
this should be fixed in latest version
